spring:
  application.name: Filmorate
  datasource:
    url: jdbc:postgresql://localhost:5432/filmorate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

